In [9]:
import os
import requests
import pandas as pd
import geopandas as gpd
import numpy as np
import pickle
from loguru import logger

from popframe.preprocessing.level_filler import LevelFiller
from popframe.models.region import Region
from idu_clients import UrbanAPI

URBAN_API = 'http://10.32.1.107:5300'
POPULATION_COUNT_INDICATOR_ID = 1
DEFAULT_CRS = 4326

def get_territories_population(territories_gdf : gpd.GeoDataFrame):
    res = requests.get(f'{URBAN_API}/api/v1/indicator/{POPULATION_COUNT_INDICATOR_ID}/values')
    res_df = pd.DataFrame(res.json())
    res_df = res_df[res_df['territory'].apply(lambda x: x['id'] if isinstance(x, dict) else None).isin(territories_gdf.index)]
    res_df = (
        res_df
        .groupby(res_df['territory'].apply(lambda x: x['id'] if isinstance(x, dict) else None))
        .agg({'value': 'last'})
        .rename(columns={'value': 'population'})
    )
    return territories_gdf[['geometry', 'name']].merge(res_df, left_index=True, right_index=True)

def get_country_regions(country_id : int) -> pd.DataFrame:
    res = requests.get(f'{URBAN_API}/api/v1/all_territories', {
        'parent_id':country_id
    })
    return gpd.GeoDataFrame.from_features(res.json()['features'], crs=DEFAULT_CRS).set_index('territory_id', drop=True)

def get_countries_without_geometry() -> pd.DataFrame:
    res = requests.get(f'{URBAN_API}/api/v1/all_territories_without_geometry')
    return pd.DataFrame(res.json()).set_index('territory_id', drop=True)

def get_regions():
    countries = get_countries_without_geometry()
    countries_ids = countries.index
    countries_regions = [get_country_regions(country_id) for country_id in countries_ids]
    return pd.concat(countries_regions)


def get_territories(parent_id : int | None = None, all_levels = False, geometry : bool = False) -> pd.DataFrame | gpd.GeoDataFrame:
    res = requests.get(URBAN_API + f'/api/v1/all_territories{"" if geometry else "_without_geometry"}', {
        'parent_id': parent_id,
        'get_all_levels': all_levels
    })
    res_json = res.json()
    if geometry:
        gdf = gpd.GeoDataFrame.from_features(res_json, crs=DEFAULT_CRS)
        return gdf.set_index('territory_id', drop=True)
    df = pd.DataFrame(res_json)
    return df.set_index('territory_id', drop=True)

def load_towns(region_id: int) -> gpd.GeoDataFrame:
    territories_gdf = get_territories(region_id, all_levels = True, geometry=True)
    towns_gdf = territories_gdf[territories_gdf['is_city'] == True]
    towns_gdf['geometry'] = towns_gdf['geometry'].representative_point()
    towns_gdf = get_territories_population(towns_gdf)
    towns_gdf['id'] = towns_gdf.index
    level_filler = LevelFiller(towns=towns_gdf)
    towns = level_filler.fill_levels()
    return towns

def load_ter(region_id: int) -> gpd.GeoDataFrame:
    # Загружаем данные территорий
    territories_gdf = get_territories(region_id, all_levels=True, geometry=True)
    territories_gdf = territories_gdf[territories_gdf['is_city'] == False]
    
    # Загружаем данные региона и выбираем нужный регион
    regions = get_regions()
    region = regions.loc[[region_id]]
    
    # Объединяем region и territories_gdf
    combined_gdf = gpd.GeoDataFrame(pd.concat([region, territories_gdf], ignore_index=True))
    
    return combined_gdf

In [5]:
def get_territories(parent_id : int | None = None, all_levels = False, geometry : bool = False) -> pd.DataFrame | gpd.GeoDataFrame:
    res = requests.get(URBAN_API + f'/api/v1/all_territories{"" if geometry else "_without_geometry"}', {
        'parent_id': parent_id,
        'get_all_levels': all_levels
    })
    res_json = res.json()
    if geometry:
        gdf = gpd.GeoDataFrame.from_features(res_json, crs=DEFAULT_CRS)
        return gdf.set_index('territory_id', drop=True)
    df = pd.DataFrame(res_json)
    return df.set_index('territory_id', drop=True)

territories_gdf = get_territories(region_id, all_levels = True, geometry=True)
towns_gdf = territories_gdf[territories_gdf['is_city'] == True]
towns_gdf['geometry'] = towns_gdf['geometry'].representative_point()
towns_gdf

/Users/mvin/Code/PopFrame_API/.venv/lib/python3.10/site-packages/geopandas/geodataframe.py:1819: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

,geometry,territory_type,parent_id,name,level,properties,admin_center,okato_code,oktmo_code,is_city,created_at,updated_at
territory_id,,,,,,,,,,,,
207,POINT (33.75892 59.36226),"{'territory_type_id': 8, 'name': 'Деревня'}",6,Болото,5,{},NaN,41203816004,41603416106,True,2024-06-16T21:35:40.801621Z,2024-11-14T12:14:48.604968Z
208,POINT (33.786 59.47517),"{'territory_type_id': 8, 'name': 'Деревня'}",6,Большой Остров,5,{},NaN,41203816020,41603416111,True,2024-06-16T21:35:40.801621Z,2024-11-14T12:14:27.303933Z
209,POINT (33.79236 59.47356),"{'territory_type_id': 8, 'name': 'Деревня'}",6,Бор,5,{},1.0,41203816001,41603416101,True,2024-06-16T21:35:40.801621Z,2024-11-14T12:14:27.664303Z
210,POINT (33.77572 59.44249),"{'territory_type_id': 8, 'name': 'Деревня'}",6,Бороватое,5,{},NaN,41203816005,41603416116,True,2024-06-16T21:35:40.801621Z,2024-11-14T12:14:28.005680Z
211,POINT (33.67728 59.32819),"{'territory_type_id': 8, 'name': 'Деревня'}",6,Бочево,5,{},NaN,41203816003,41603416121,True,2024-06-16T21:35:40.801621Z,2024-11-14T12:14:28.342778Z
...,...,...,...,...,...,...,...,...,...,...,...,...
3133,POINT (31.23421 59.17021),"{'territory_type_id': 8, 'name': 'Деревня'}",205,Апраксин Бор,5,{},NaN,41248844010,41648444111,True,2024-06-16T21:35:40.801621Z,2024-11-14T12:14:25.425923Z
3134,POINT (31.31924 59.18702),"{'territory_type_id': 8, 'name': 'Деревня'}",205,Александровка,5,{},NaN,41248844002,41648444106,True,2024-06-16T21:35:40.801621Z,2024-11-14T12:14:25.790752Z
3135,POINT (31.47462 59.29408),"{'territory_type_id': 8, 'name': 'Деревня'}",205,Большая Горка,5,{},NaN,41248860002,41648444131,True,2024-06-16T21:35:40.801621Z,2024-11-14T12:14:26.168020Z
3136,POINT (31.46265 59.30308),"{'territory_type_id': 8, 'name': 'Деревня'}",205,Дроздово,5,{},NaN,41248860003,41648444146,True,2024-06-16T21:35:40.801621Z,2024-11-14T12:14:26.553524Z
3137,POINT (31.45747 59.30139),"{'territory_type_id': 8, 'name': 'Деревня'}",205,Большая Кунесть,5,{},NaN,41248860009,41648444136,True,2024-06-16T21:35:40.801621Z,2024-11-14T12:14:26.922021Z

In [10]:
region_id = 1
towns = load_towns(region_id)

/Users/mvin/Code/PopFrame_API/.venv/lib/python3.10/site-packages/geopandas/geodataframe.py:1819: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

In [11]:
towns

,geometry,id,name,population,level
territory_id,,,,,
207,POINT (33.75892 59.36226),207,Болото,10,Малое сельское поселение
208,POINT (33.786 59.47517),208,Большой Остров,68,Малое сельское поселение
209,POINT (33.79236 59.47356),209,Бор,1734,Большое сельское поселение
210,POINT (33.77572 59.44249),210,Бороватое,10,Малое сельское поселение
211,POINT (33.67728 59.32819),211,Бочево,10,Малое сельское поселение
...,...,...,...,...,...
3133,POINT (31.23421 59.17021),3133,Апраксин Бор,313,Среднее сельское поселение
3134,POINT (31.31924 59.18702),3134,Александровка,313,Среднее сельское поселение
3135,POINT (31.47462 59.29408),3135,Большая Горка,313,Среднее сельское поселение
3136,POINT (31.46265 59.30308),3136,Дроздово,5,Малое сельское поселение
3137,POINT (31.45747 59.30139),3137,Большая Кунесть,5,Малое сельское поселение

In [35]:
BASE_URL = os.environ['URBAN_API'] if 'URBAN_API' in os.environ else 'http://10.32.1.107:5300/api/v1'
BASE_URL

'http://10.32.1.107:5300/api/v1'

In [23]:
project_id = 23
token = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbkB0ZXN0LnJ1IiwiaWF0IjoxNzMwMzcyODEwLCJleHAiOjE3MzA5Nzc2MTB9.ns1MdEamQ30vNgSBFaHsObsliZlfmxNCiviWUgMS0q0'

In [37]:
territory_response = requests.get(
    f"{BASE_URL}/projects/{project_id}/territory",
    headers={"Authorization": f"Bearer {token}"}
)
if territory_response.status_code != 200:
    raise Exception("Error retrieving territory geometry")

# Extracting only the polygon geometry
territory_data = territory_response.json()
territory_geometry = territory_data["geometry"]

# Converting the territory geometry to GeoDataFrame
territory_feature = {
    'type': 'Feature',
    'geometry': territory_geometry,
    'properties': {}
}
territory_feature

{'type': 'Feature',
 'geometry': {'type': 'MultiPolygon',
  'coordinates': [[[[30.0059032, 59.3540961],
     [30.0140259, 59.3541968],
     [30.0144851, 59.3537473],
     [30.0171668, 59.3511223],
     [30.015342, 59.350238],
     [30.0138596, 59.3495195],
     [30.0143785, 59.3491353],
     [30.0162724, 59.347733],
     [30.0191619, 59.3486876],
     [30.0208661, 59.3471504],
     [30.0304709, 59.3498384],
     [30.0326995, 59.3498646],
     [30.0352931, 59.3498669],
     [30.0363521, 59.3497148],
     [30.0375074, 59.3497531],
     [30.03943, 59.3505102],
     [30.0394118, 59.3508378],
     [30.0398624, 59.3508471],
     [30.0470199, 59.3509127],
     [30.0470987, 59.3509101],
     [30.0494094, 59.3508325],
     [30.0500785, 59.35081],
     [30.0599024, 59.3504801],
     [30.060686, 59.353232],
     [30.0538542, 59.3648126],
     [30.0461724, 59.3637629],
     [30.0425815, 59.3663932],
     [30.0417092, 59.3670321],
     [30.0409734, 59.3671498],
     [30.0372675, 59.3677428],
     [30.0330454, 59.3664227],
     [30.032496, 59.3662509],
     [30.0287702, 59.3650859],
     [30.0193074, 59.367382],
     [30.0177839, 59.3660372],
     [30.0257876, 59.36373],
     [30.025101, 59.3618383],
     [30.0283411, 59.361729],
     [30.0285771, 59.3628334],
     [30.0349286, 59.3629428],
     [30.034702, 59.3620422],
     [30.0346067, 59.3616634],
     [30.0182345, 59.3587545],
     [30.0179306, 59.3589847],
     [30.0158956, 59.3605261],
     [30.0106814, 59.3597059],
     [30.0099518, 59.3581092],
     [30.0040991, 59.357103],
     [30.0059032, 59.3540961]]]]},
 'properties': {}}