In [1]:
from idu_clients import UrbanAPI

In [2]:
urban_api = UrbanAPI('http://10.32.1.107:5300')
regions = await urban_api.get_regions()
regions

,geometry,territory_type,parent_id,name,level,properties,admin_center,okato_code,oktmo_code,created_at,updated_at
territory_id,,,,,,,,,,,
1,"MULTIPOLYGON (((34.32572 59.19331, 34.32541 59...","{'territory_type_id': 1, 'name': 'Субъект Феде...",12639,Ленинградская область,2,"{'Малые города': 15, 'Крупные города': 0, 'Вуз...",None,41000000000,None,2024-06-16T21:35:40.801621Z,2024-06-16T21:35:40.801621Z
3138,"MULTIPOLYGON (((29.42576 60.19074, 29.42719 60...","{'territory_type_id': 17, 'name': 'Город федер...",12639,Санкт-Петербург,2,"{'Малые города': 10, 'Крупные города': 0, 'Чис...",None,40000000000,None,2024-06-16T21:35:40.801621Z,2024-06-16T21:35:40.801621Z
3268,"MULTIPOLYGON (((36.80310 55.44083, 36.81136 55...","{'territory_type_id': 17, 'name': 'Город федер...",12639,Москва,2,"{'Малые города': 16, 'Крупные города': 1, 'Чис...",None,45000000000,None,2024-06-16T21:35:40.801621Z,2024-06-16T21:35:40.801621Z
3427,"MULTIPOLYGON (((41.16810 50.77451, 41.17850 50...","{'territory_type_id': 1, 'name': 'Субъект Феде...",12639,Волгоградская область,2,"{'Малые города': 32, 'Крупные города': 1, 'Вуз...",None,18000000000,None,2024-06-16T21:35:40.801621Z,2024-06-16T21:35:40.801621Z
3902,"POLYGON ((35.89856 53.85018, 35.90015 53.84679...","{'territory_type_id': 1, 'name': 'Субъект Феде...",12639,Тульская область,2,"{'Малые города': 20, 'Крупные города': 1, 'Вуз...",None,70000000000,None,2024-06-16T21:35:40.801621Z,2024-06-16T21:35:40.801621Z
4013,"MULTIPOLYGON (((70.35830 57.90031, 70.35880 57...","{'territory_type_id': 1, 'name': 'Субъект Феде...",12639,Омская область,2,"{'Малые города': 30, 'Крупные города': 0, 'Вуз...",None,52000000000,None,2024-06-16T21:35:40.801621Z,2024-06-16T21:35:40.801621Z
4437,"MULTIPOLYGON (((36.53049 45.19920, 36.53270 45...","{'territory_type_id': 1, 'name': 'Субъект Феде...",12639,Краснодарский край,2,"{'Малые города': 142, 'Крупные города': 2, 'Ву...",None,30000000000,None,2024-06-16T21:35:40.801621Z,2024-06-16T21:35:40.801621Z
4882,"MULTIPOLYGON (((64.82719 57.29312, 64.86016 57...","{'territory_type_id': 1, 'name': 'Субъект Феде...",12639,Тюменская область,2,"{'Малые города': 21, 'Крупные города': 1, 'Вуз...",None,71000000000,None,2024-06-16T21:35:40.801621Z,2024-06-16T21:35:40.801621Z
5188,"POLYGON ((35.14850 55.95750, 35.14878 55.95714...","{'territory_type_id': 1, 'name': 'Субъект Феде...",12639,Московская область,2,"{'Малые города': 99, 'Крупные города': 1, 'Вуз...",None,46000000000,None,2024-06-16T21:35:40.801621Z,2024-06-16T21:35:40.801621Z
12640,"POLYGON ((38.68402 44.95142, 38.72123 44.95065...","{'territory_type_id': 1, 'name': 'Субъект Феде...",12639,Республика Адыгея,2,{},None,None,253256,2024-10-16T12:32:55.991110Z,2024-10-16T12:32:55.991110Z
12701,"MULTIPOLYGON (((35.26960 65.33598, 35.34353 65...","{'territory_type_id': 1, 'name': 'Субъект Феде...",12639,Архангельская область,2,{},None,None,140337,2024-10-16T13:10:23.703706Z,2024-10-16T13:10:23.703706Z
12769,"MULTIPOLYGON (((44.96098 48.27086, 45.05553 48...","{'territory_type_id': 1, 'name': 'Субъект Феде...",12639,Астраханская область,2,{},None,None,112819,2024-10-16T13:31:55.517790Z,2024-10-16T13:31:55.517790Z
12910,"MULTIPOLYGON (((31.24191 53.02881, 31.24196 53...","{'territory_type_id': 1, 'name': 'Субъект Феде...",12639,Брянская область,2,{},None,None,81997,2024-10-16T13:57:35.623155Z,2024-10-16T13:57:35.623155Z
13147,"POLYGON ((32.20158 45.39689, 32.20272 45.38293...","{'territory_type_id': 1, 'name': 'Субъект Феде...",12639,Республика Крым,2,{},None,None,3795586,2024-10-16T14:09:18.326828Z,2024-10-16T14:09:18.326828Z
13148,"POLYGON ((39.37404 56.81996, 39.37727 56.81120...","{'territory_type_id': 1, 'name': 'Субъект Феде...",12639,Ивановская область,2,{},None,None,85617,2024-10-16T14:09:18.326828Z,2024-10-16T14:09:18.326828Z
13292,"POLYGON ((19.40417 54.60390, 19.46856 54.56403...","{'territory_type_id': 1, 'name': 'Субъект Феде...",12639,Калининградская область,2,{},None,None,103906,2024-10-16T14:55:07.742252Z,2024-10-16T14:55:07.742252Z
13315,"POLYGON ((33.44139 54.05471, 33.44152 54.05421...","{'territory_type_id': 1, 'name': 'Субъект Феде...",12639,Калужская область,2,{},None,None,81995,2024-10-16T14:57:14.533904Z,2024-10-16T14:57:14.533904Z
13368,"POLYGON ((29.30615 61.32925, 29.31595 61.32288...","{'territory_type_id': 1, 'name': 'Субъект Феде...",12639,Республика Карелия,2,{},None,None,393980,2024-10-16T15:06:02.717129Z,2024-10-16T15:06:02.717129Z
13473,"MULTIPOLYGON (((84.44789 56.04157, 84.44800 56...","{'territory_type_id': 1, 'name': 'Субъект Феде...",12639,Кемеровская область,2,{},None,None,144763,2024-10-16T15:08:55.024225Z,2024-10-16T15:08:55.024225Z
13517,"POLYGON ((59.20379 63.02760, 59.20471 63.02718...","{'territory_type_id': 1, 'name': 'Субъект Феде...",12639,Ханты-Мансийский автономный округ,2,{},None,None,140296,2024-10-16T16:07:46.518961Z,2024-10-16T16:07:46.518961Z
13623,"MULTIPOLYGON (((46.26378 60.23715, 46.26486 60...","{'territory_type_id': 1, 'name': 'Субъект Феде...",12639,Кировская область,2,{},None,None,115100,2024-10-17T15:53:27.212282Z,2024-10-17T15:53:27.212282Z
13910,"POLYGON ((45.39935 64.17492, 45.46084 64.13675...","{'territory_type_id': 1, 'name': 'Субъект Феде...",12639,Республика Коми,2,{},None,None,115136,2024-10-16T16:20:31.520192Z,2024-10-16T16:20:31.520192Z
14088,"POLYGON ((40.39010 57.39873, 40.39234 57.39656...","{'territory_type_id': 1, 'name': 'Субъект Феде...",12639,Костромская область,2,{},None,None,85963,2024-10-16T16:26:47.905253Z,2024-10-16T16:26:47.905253Z
14203,"POLYGON ((34.08034 51.66618, 34.08043 51.66599...","{'territory_type_id': 1, 'name': 'Субъект Феде...",12639,Курская область,2,{},None,None,72223,2024-10-16T16:37:25.343864Z,2024-10-16T16:37:25.343864Z
14552,"POLYGON ((28.41579 68.91545, 28.42913 68.90780...","{'territory_type_id': 1, 'name': 'Субъект Феде...",12639,Мурманская область,2,{},None,None,2099216,2024-10-16T16:47:56.597834Z,2024-10-16T16:47:56.597834Z
14589,"MULTIPOLYGON (((41.31260 68.59766, 41.45582 68...","{'territory_type_id': 1, 'name': 'Субъект Феде...",12639,Ненецкий автономный округ,2,{},None,None,274048,2024-10-16T16:57:16.894068Z,2024-10-16T16:57:16.894068Z
14611,"POLYGON ((41.77648 55.09864, 41.78384 55.09056...","{'territory_type_id': 1, 'name': 'Субъект Феде...",12639,Нижегородская область,2,{},None,None,72195,2024-10-16T16:59:19.620876Z,2024-10-16T16:59:19.620876Z
14663,"POLYGON ((29.61873 58.25167, 29.63407 58.24202...","{'territory_type_id': 1, 'name': 'Субъект Феде...",12639,Новгородская область,2,{},None,None,89331,2024-10-16T17:04:40.555462Z,2024-10-16T17:04:40.555462Z
14759,"POLYGON ((34.79197 52.86571, 34.79385 52.86228...","{'territory_type_id': 1, 'name': 'Субъект Феде...",12639,Орловская область,2,{},None,None,72224,2024-10-16T17:10:59.422873Z,2024-10-16T17:10:59.422873Z
15010,"MULTIPOLYGON (((42.08174 53.74800, 42.08525 53...","{'territory_type_id': 1, 'name': 'Субъект Феде...",12639,Пензенская область,2,{},None,None,72182,2024-10-16T17:19:11.962635Z,2024-10-16T17:19:11.962635Z
15329,"POLYGON ((51.77238 60.58004, 51.81480 60.57583...","{'territory_type_id': 1, 'name': 'Субъект Феде...",12639,Пермский край,2,{},None,None,115135,2024-10-16T17:25:32.714429Z,2024-10-16T17:25:32.714429Z
15373,"POLYGON ((27.31748 57.58000, 27.31750 57.57998...","{'territory_type_id': 1, 'name': 'Субъект Феде...",12639,Псковская область,2,{},None,None,155262,2024-10-16T17:32:34.609019Z,2024-10-16T17:32:34.609019Z
15477,"MULTIPOLYGON (((47.93044 53.36160, 47.93348 53...","{'territory_type_id': 1, 'name': 'Субъект Феде...",12639,Самарская область,2,{},None,None,72194,2024-10-16T17:43:25.511226Z,2024-10-16T17:43:25.511226Z
15811,"POLYGON ((42.50404 51.66518, 42.50426 51.66298...","{'territory_type_id': 1, 'name': 'Субъект Феде...",12639,Саратовская область,2,{},None,None,72193,2024-10-16T17:48:23.147175Z,2024-10-16T17:48:23.147175Z
16141,"POLYGON ((33.09120 44.57529, 33.09234 44.56113...","{'territory_type_id': 17, 'name': 'Город федер...",12639,Севастополь,2,{},None,None,3788485,2024-10-16T17:55:49.873089Z,2024-10-16T17:55:49.873089Z
16152,"POLYGON ((30.75157 54.80952, 30.75271 54.80744...","{'territory_type_id': 1, 'name': 'Субъект Феде...",12639,Смоленская область,2,{},None,None,81996,2024-10-16T17:55:56.910900Z,2024-10-16T17:55:56.910900Z
16336,"POLYGON ((39.91569 52.70885, 39.92159 52.70844...","{'territory_type_id': 1, 'name': 'Субъект Феде...",12639,Тамбовская область,2,{},None,None,72180,2024-10-16T18:05:36.086640Z,2024-10-16T18:05:36.086640Z
16367,"MULTIPOLYGON (((47.23702 54.84680, 47.23720 54...","{'territory_type_id': 1, 'name': 'Субъект Феде...",12639,Республика Татарстан,2,{},None,None,79374,2024-10-16T18:05:36.086640Z,2024-10-16T18:05:36.086640Z
17324,"POLYGON ((30.72839 56.78077, 30.74208 56.77468...","{'territory_type_id': 1, 'name': 'Субъект Феде...",12639,Тверская область,2,{},None,None,2095259,2024-10-16T18:17:13.094289Z,2024-10-16T18:17:13.094289Z
17365,"MULTIPOLYGON (((45.79672 53.98650, 45.79767 53...","{'territory_type_id': 1, 'name': 'Субъект Феде...",12639,Ульяновская область,2,{},None,None,72192,2024-10-16T18:17:13.094289Z,2024-10-16T18:17:13.094289Z
17533,"POLYGON ((38.26810 56.52477, 38.26933 56.52293...","{'territory_type_id': 1, 'name': 'Субъект Феде...",12639,Владимирская область,2,{},None,None,72197,2024-10-16T18:23:07.700636Z,2024-10-16T18:23:07.700636Z
17661,"POLYGON ((34.71909 59.07780, 34.78714 59.05927...","{'territory_type_id': 1, 'name': 'Субъект Феде...",12639,Вологодская область,2,{},None,None,115106,2024-10-16T18:27:48.260675Z,2024-10-16T18:27:48.260675Z
17721,"POLYGON ((38.13775 51.63232, 38.13884 51.63147...","{'territory_type_id': 1, 'name': 'Субъект Феде...",12639,Воронежская область,2,{},None,None,72181,2024-10-16T18:32:01.502168Z,2024-10-16T18:32:01.502168Z
18198,"POLYGON ((62.00044 65.71774, 62.00224 65.71717...","{'territory_type_id': 1, 'name': 'Субъект Феде...",12639,Ямало-Ненецкий автономный округ,2,{},None,None,191706,2024-10-16T18:37:24.620393Z,2024-10-16T18:37:24.620393Z
18212,"POLYGON ((37.32791 58.23664, 37.33503 58.22523...","{'territory_type_id': 1, 'name': 'Субъект Феде...",12639,Ярославская область,2,{},None,None,81994,2024-10-16T18:42:05.738201Z,2024-10-16T18:42:05.738201Z

In [3]:
region = regions.loc[[4882]]
region

,geometry,territory_type,parent_id,name,level,properties,admin_center,okato_code,oktmo_code,created_at,updated_at
territory_id,,,,,,,,,,,
4882,"MULTIPOLYGON (((64.82719 57.29312, 64.86016 57...","{'territory_type_id': 1, 'name': 'Субъект Феде...",12639,Тюменская область,2,"{'Малые города': 21, 'Крупные города': 1, 'Вуз...",None,71000000000,None,2024-06-16T21:35:40.801621Z,2024-06-16T21:35:40.801621Z

In [4]:
local_crs = region.estimate_utm_crs()
local_crs

<Projected CRS: EPSG:32642>
Name: WGS 84 / UTM zone 42N
Axis Info [cartesian]:
- E[east]: Easting (metre)
- N[north]: Northing (metre)
Area of Use:
- name: Between 66°E and 72°E, northern hemisphere between equator and 84°N, onshore and offshore. Afghanistan. India. Kazakhstan. Kyrgyzstan. Pakistan. Russian Federation. Tajikistan. Uzbekistan.
- bounds: (66.0, 0.0, 72.0, 84.0)
Coordinate Operation:
- name: UTM zone 42N
- method: Transverse Mercator
Datum: World Geodetic System 1984 ensemble
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich